# Generated by Django 6.0.6 on 2026-06-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_cards', to='core.menuitem', verbose_name='Item de menu relacionado')),
            ],
            options={
                'verbose_name': 'Tarjeta resumen',
                'verbose_name_plural': 'Tarjetas resumen',
                'ordering': ['order', 'title'],
            },
        ),
    ]
